
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/internal/scheduler/dispatch"


)

var tests = []testing.InternalTest{

	{"TestBuildDecision_PreferRequestedExecutionHW", _test.TestBuildDecision_PreferRequestedExecutionHW},

	{"TestBuildDecision_UseStableGPUDeviceID", _test.TestBuildDecision_UseStableGPUDeviceID},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/internal/scheduler/dispatch"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

