
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/test/integration"


)

var tests = []testing.InternalTest{

	{"TestIntegration_JobModel", _test.TestIntegration_JobModel},

	{"TestIntegration_SegmentModel", _test.TestIntegration_SegmentModel},

	{"TestIntegration_SegmentUploadStatus", _test.TestIntegration_SegmentUploadStatus},

	{"TestIntegration_JobStatusTransitions", _test.TestIntegration_JobStatusTransitions},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/test/integration"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

