
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/internal/usecase/transcode"


)

var tests = []testing.InternalTest{

	{"TestCreateJobUseCase_Execute", _test.TestCreateJobUseCase_Execute},

	{"TestCreateJobUseCase_ExecuteBuildRequestOverride", _test.TestCreateJobUseCase_ExecuteBuildRequestOverride},

	{"TestCreateJobUseCase_ExecuteSupportsGRPCAndMQCallbackURL", _test.TestCreateJobUseCase_ExecuteSupportsGRPCAndMQCallbackURL},

	{"TestCreateJobUseCase_ExecuteRejectsInvalidCallbackURL", _test.TestCreateJobUseCase_ExecuteRejectsInvalidCallbackURL},

	{"TestCreateJobUseCase_ExecuteRejectsUnsupportedFields", _test.TestCreateJobUseCase_ExecuteRejectsUnsupportedFields},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/internal/usecase/transcode"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

