
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/internal/scheduler/filter"


)

var tests = []testing.InternalTest{

	{"TestApply_MatchPreferredExecutionHW", _test.TestApply_MatchPreferredExecutionHW},

	{"TestApply_RejectMismatchedPreferredExecutionHW", _test.TestApply_RejectMismatchedPreferredExecutionHW},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/internal/scheduler/filter"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

