
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/test/benchmark"


)

var tests = []testing.InternalTest{

}

var benchmarks = []testing.InternalBenchmark{

	{"BenchmarkBuildRenditions", _test.BenchmarkBuildRenditions},

	{"BenchmarkRenderSegmentName", _test.BenchmarkRenderSegmentName},

	{"BenchmarkQualityLabelFromHeight", _test.BenchmarkQualityLabelFromHeight},

	{"BenchmarkMapRepIDToRendition", _test.BenchmarkMapRepIDToRendition},

	{"BenchmarkCalculateWidth", _test.BenchmarkCalculateWidth},

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/test/benchmark"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

