
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/test/e2e"


)

var tests = []testing.InternalTest{

	{"TestE2E_TranscodePipeline", _test.TestE2E_TranscodePipeline},

	{"TestE2E_SegmentNamingConsistency", _test.TestE2E_SegmentNamingConsistency},

	{"TestE2E_QualityLabelMapping", _test.TestE2E_QualityLabelMapping},

	{"TestE2E_MapRepIDToRendition", _test.TestE2E_MapRepIDToRendition},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/test/e2e"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

