
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/internal/bootstrap"


)

var tests = []testing.InternalTest{

	{"TestRuntimeConfigLoad", _test.TestRuntimeConfigLoad},

	{"TestFFprobeExists", _test.TestFFprobeExists},

	{"TestApplicationRunCancelledContext", _test.TestApplicationRunCancelledContext},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/internal/bootstrap"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

