
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "hvc/internal/callback"


)

var tests = []testing.InternalTest{

	{"TestResolveTargetsUsesHTTPJobOverrideCallbackURL", _test.TestResolveTargetsUsesHTTPJobOverrideCallbackURL},

	{"TestResolveTargetsUsesGRPCJobOverrideCallbackURL", _test.TestResolveTargetsUsesGRPCJobOverrideCallbackURL},

	{"TestResolveTargetsUsesMQJobOverrideCallbackURL", _test.TestResolveTargetsUsesMQJobOverrideCallbackURL},

	{"TestResolveTargetsFallsBackToRuntimeHTTPURL", _test.TestResolveTargetsFallsBackToRuntimeHTTPURL},

	{"TestDefaultTimeoutMS", _test.TestDefaultTimeoutMS},

	{"TestCallbackTargetString", _test.TestCallbackTargetString},

	{"TestParseTaskCallbackTarget", _test.TestParseTaskCallbackTarget},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "hvc/internal/callback"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

